server:
  port: 88
spring:
  application:
    name: mall-gateway
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos服务端地址
    gateway:
      routes:
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}